version: "3.9"
services:
  apache:
    build:
      context: ..
      dockerfile: docker/apache/Dockerfile
    ports:
      - "${APACHE_HOST_PORT:-8081}:80"
    enviroment:
      - APP_env=prod
    restart: unless-stopped
